export const CIV_KEY_TO_NAME = new Map<string, string>([
    ["ab", "Abbasid Dynasty"],
    ["ay", "Ayyubids"],
    ["by", "Byzantines"],
    ["ch", "Chinese"],
    ["de", "Delhi Sultanate"],
    ["en", "English"],
    ["fr", "French"],
    ["hr", "Holy Roman Empire"],
    ["ja", "Japanese"],
    ["je", "Jeanne D'Arc"],
    ["ma", "Malians"],
    ["mo", "Mongols"],
    ["od", "Order of the Dragon"],
    ["ot", "Ottomans"],
    ["ru", "Rus"],
    ["zx", "Zhu Xi's Legacy"],
    ["kt", "Knights Templar"],
    ["hl", "House of Lancaster"],
]);